import "./globals.css";
import NavBar from "@/components/layout/NavBar"

export const metadata = {
  title: "Domo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="bg-background pt-[70px] p-4">
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
